export const QCM_INITIALISATION = 'QCM_INITIALISATION';
export const QUESTION_CHANGE = 'QUESTION_CHANGE';
export const QUESTION_VALID_SUBMIT = 'QUESTION_VALID_SUBMIT';
export const QUESTION_INVALID_SUBMIT = 'QUESTION_INVALID_SUBMIT';
export const QCM_VALID_SUBMIT = 'QCM_VALID_SUBMIT';
export const QCM_INVALID_SUBMIT = 'QCM_INVALID_SUBMIT';